spring:
  datasource:
    url: jdbc:mysql://45.76.206.232:3306/wushan?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: dev
    password: jdfohewk
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    host: 45.32.18.248
    port: 6379
    password: jdfohewk


server:
  port: 80